application: dart-gdg-nyc-462
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  script: main.application
  secure: always
- url: /_ah/spi/.*
  script: hello_api.APPLICATION
- url: /style
  static_dir: style
- url: /js
  static_dir: js

libraries:
- name: endpoints
  version: 1.0
- name: webapp2
  version: latest
- name: jinja2
  version: latest